name: binaries

on:
  workflow_dispatch:
  push:
    branches:
    tags:

env:
  go_version: 1.22.12

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    with:
      go_version: "1.22.12"
      ubuntu_version: "24.04"
      artifact_name: "avalanchego"

  build-verify:
    uses: ./.github/workflows/build.yaml
    with:
      go_version: "1.22.12"
      ubuntu_version: "24.04"
      artifact_name: "avalanchego-verify"

  release:
    runs-on: ubuntu-24.04
    needs: [build, build-verify]
    if: github.ref_type == 'tag'
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v3

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Verify build
        run: |
          HASH_MAIN=$(sha256sum artifacts/avalanchego/avalanchego | awk '{print $1}')
          HASH_VERIFY=$(sha256sum artifacts/avalanchego-verify/avalanchego | awk '{print $1}')
          
          if [ "$HASH_MAIN" = "$HASH_VERIFY" ]; then
            echo "Hashes match"
          else
            echo "Hashes don't match"
            exit 1
          fi

      - name: Set release variables
        run: |
          RELEASE_TAG="${{ github.ref_name }}"
          echo "RELEASE_TAG=${RELEASE_TAG}" >> $GITHUB_ENV
          echo "ARTIFACT_NAME=go-flare-${RELEASE_TAG}-linux-amd64.zip" >> $GITHUB_ENV

      - name: Package build for release
        run: |
          cd artifacts/avalanchego
          zip -r ../../${{ env.ARTIFACT_NAME }} .

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.8.1

      - name: Sign release binary
        env:
          COSIGN_EXPERIMENTAL: 1
        run: |
          cosign sign-blob --yes \
            --output-signature ${{ env.ARTIFACT_NAME }}.sig \
            --output-certificate ${{ env.ARTIFACT_NAME }}.pem \
            ${{ env.ARTIFACT_NAME }}

      - name: Verify release binary signature
        env:
          COSIGN_EXPERIMENTAL: 1
        run: |
          cosign verify-blob \
            --certificate ${{ env.ARTIFACT_NAME }}.pem \
            --certificate-identity=https://github.com/${{ github.repository }}/.github/workflows/build-binary.yaml@${{ github.ref }} \
            --certificate-oidc-issuer=https://token.actions.githubusercontent.com \
            --signature ${{ env.ARTIFACT_NAME }}.sig \
            ${{ env.ARTIFACT_NAME }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body: "TODO"
          files: ${{ env.ARTIFACT_NAME }}*

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-bin
          path: ${{ env.ARTIFACT_NAME }}